### ISSUE TITLE
Downloads image instead of whole video

### ISSUE THREAD

**Issue by joker45op** [JackhammerYT/RedDownloader#13]
I am passing url of meme video posted on reddit,
The video is short. But when it downloads and identify post type it is image.
What can be the solution.... ?

Example post url = https://www.reddit.com/r/SaimanSays/comments/vfpzbu/अचछ/?utm_medium=android_app&utm_source=share

**Comment by JackhammerYT** [comment]
Thank you for bringing this issue to notice, the uploaded file is a gif file so I'll immediately ready a fix and a way to retrieve file in .Gif formart

**Comment by joker45op** [comment]
Thank you for the update.
I am new and i am having a project for that I needed it, Reddit to Instagram uploader bot.
Once again thank you.
