### ISSUE TITLE
Unable to get the video format

### ISSUE THREAD

**Issue by kents00** [JackhammerYT/RedDownloader#18]
Hello, mate. I recently discovered a bug in which I will download the video but only in audio format.
`from RedDownloader import RedDownloader`
`url="https://www.reddit.com/r/projectzomboid/comments/wfaybk/sunday_driver_is_a_meme/utm_source=share&utm_medium=web2x&context=3"`
`RedDownloader.Download(url, quality=1080)`
it will going to download and then after fetching the audio and video it will merge into an `mp3` file why there is no Video file?
[Merge into mp4](https://ibb.co/8811vj0) and [What I've got](https://ibb.co/7n8Gd1k)

**Comment by JackhammerYT** [comment]
Could not reproduce the error, and successfully downloaded the video

Test Code:
```py
from RedDownloader import RedDownloader

url = "https://www.reddit.com/r/projectzomboid/comments/wfaybk/sunday_driver_is_a_meme/"

RedDownloader.Download(url , quality=1080)
```

Output:

![Screenshot 2022-08-05 012808](https://user-images.githubusercontent.com/49639514/182941646-c18a84fb-dc60-4997-b1de-a79cc3d16785.png)

**Comment by kents00** [comment]
Thank you; it worked. I reinstalled the Library, and everything is good now.
