### ISSUE TITLE
Downloaded video name not correct

### ISSUE THREAD

**Issue by n-eari** [JackhammerYT/RedDownloader#20]
With some posts, when I download the video, the name of the file comes out as "Video.mp4" and not "downloaed.mp4". Even when I set the output parameter as something else, it still results in "Video.mp4".

The code im running:
`RedDownloader.Download(url = link, quality = 360)`
where link = https://www.reddit.com/r/Damnthatsinteresting/comments/woo9hf/a_nanobot_helping_a_sperm_with_motility_issues/?utm_source=share&utm_medium=web2x&context=3

The output:
<img width="689" alt="Screenshot 2022-08-15 120604" src="https://user-images.githubusercontent.com/102254245/184625071-9f1b2ecb-095d-4ed8-9630-352e046a3a28.png">

edit: this seems to be the case for videos w/o sound. i tried to work around this issue by setting the output parameter to "Video", so no matter if the video has audio or not, it will be called "Video.mp4", however, this doesnt work eitheir. if the video has sound and the output is set to "Video", the file will simply not save, even though the command line says otherwise

**Comment by n-eari** [comment]
i seemed to fix it by setting the destination parameter to "". my files were already being saved to the same destination as my .py file without this parameter, but i seems whatever is going on internally requires me to specify as ""

**Comment by JackhammerYT** [comment]
Fixed in [RedDownloader 3.3.0](https://pypi.org/project/RedDownloader/)
