### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Pggeeks** [JackhammerYT/RedDownloader#23]
This Link is Used to generate postLink:- 
https://jackhammer.pythonanywhere.com/reddit/media/downloader/
but throws **Server Error (500)** for quite sometime
Please check the issue 
@JackhammerYT

**Comment by JackhammerYT** [comment]
@JoseRaulBS and @Pggeeks The issue has been identified and fixed please update to the latest version of RedDownloader and everything else should be all right
