### ISSUE TITLE
Sorry there was an error while fetching video/audio files

### ISSUE THREAD

**Issue by LoganAC34** [JackhammerYT/RedDownloader#30]
Hi. I'm having an issue with downloading videos. It seems like i'm having a similar issue as this post: https://github.com/JackhammerYT/RedDownloader/issues/21
I'm seemingly able to download images, but not videos. 

The video i'm trying to download is this:
https://www.reddit.com/r/AnimalsBeingDerps/comments/en0ho3/excited_new_parent_playing_with_new_kittens/
Its available in 240p.

It runs though each resolution and fails, then says:
```
Sorry there was an error while fetching video/audio files

Traceback:
 Can't fetch the video file
```

my code:
`RedDownloader.Download(url, output=submission.title, destination="media\\")`

For the pictures that I can download, some of them are corrupt. I use a third party image viewer app (ImageGlass) and when I open the corrupt images, it says:
```
ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported. 
Magick.Net-Q16-OpenMP-x64:  Not a JPEG file: starts with 0x3c 0x21 '<corrupt image path>' @ error/jpeg.c/JPEGErrorHandler/348
```

When open the corrupt image in windows default image viewer, it just says "It appears that we don't support this file format."

UPDATE:
I'm letting my script crawl over my saved posts and it's downloading some videos. 
https://www.reddit.com/r/AnimalsBeingBros/comments/hv8qdh/puppy_what_are_you_doing_there_puppy/
https://www.reddit.com/r/aww/comments/hkim89/these_two_foster_puppies_rescued_from_a_hoarder/
Not sure why its failing for some but not others. 

Also, i noticed that its downloading some images but not putting a file extension and their file size is 0 bits, and when I try to delete them, it says the file doesn't exist.

**Comment by JackhammerYT** [comment]
Please refer to issue #26 

This issue is known and being worked upon.
Thank You
