### ISSUE TITLE
A problem with YouTube downloads

### ISSUE THREAD

**Issue by dylnbk** [JackhammerYT/RedDownloader#31]
Type Detected: Youtube Video
Downloading Youtube Video

Connection Error
[WinError 2] The filename, directory name, or volume label syntax is incorrect: 'Youtube title | Youtube title  | Youtube title.mp4' -> '72ac10ad93a340d5ac09ea45f7bde5b3.mp4'

I believe using the YouTube title as the file name is causing an error due to the naming convention.

Could this perhaps be updated?

`stream.download('.')` & `stream.download(self.destination)` can take a `filename=` argument.

Pytube also has a helper function [safe_filename()](https://pytube.io/en/latest/api.html#pytube.helpers.safe_filename).

**Comment by JackhammerYT** [comment]
Thanks For highlighting this issue to me, it has been patched in #33
