### ISSUE TITLE
Download files in silent mode

### ISSUE THREAD

**Issue by uN4sh** [JackhammerYT/RedDownloader#36]
Hello,

As this project is largely completed for many features, I think it is time to add a **silent mode** during downloads.
Actually, the program is by default in **verbose mode** and details all the actions performed.
```
Detected Post Type: Video
Fetching Video...
Trying resolution: 360p
Video File Downloaded Successfully
Fetching Audio...
Merging Files
Moviepy - Building video ./reddit/video.mp4.
MoviePy - Writing audio in videoTEMP_MPY_wvf_snd.mp3
MoviePy - Done.                                                                                                                         
Moviepy - Writing video ./reddit/video.mp4

Moviepy - Done !                                                                                                                        
Moviepy - video ready ./reddit/video.mp4
cleaning
./reddit/video Successfully Downloaded!
```

This mode is not very practical when you want to integrate the functionalities of this project into a larger project, which would run continuously and whose logs would be smoother.

**Comment by JackhammerYT** [comment]
@uN4sh The enhancement has been added in the latest version of RedDownloader 4.1.2 it can be installed from [here](https://pypi.org/project/RedDownloader/)

**Comment by uN4sh** [comment]
This is a nice enhancement, you did well replacing prints by a Logger Class!
