### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by I8i9** [JackhammerYT/RedDownloader#38]
a simple code like this RedDownloader.DownloadBySubreddit("memes" , 15)  gives you this eror "Unable to fetch posts
Expecting value: line 2 column 1 (char 1)"

**Comment by JackhammerYT** [comment]
@I8i9 Sorry for inconvience there was an issue on the RedDownloader Response Server which has been patched, you should be able to use the package as expected now and further steps have been taken to make sure the issue doesn't arise again. Thank You
