### ISSUE TITLE
ModuleNotFoundError:  No module named 'Utils'

### ISSUE THREAD

**Issue by otherfutures** [JackhammerYT/RedDownloader#40]
Program immediately fails & outputs the above error; it seems to not recognise the python file despite it being highlighted as correctly working in the IDE.

**Comment by JackhammerYT** [comment]
@otherfutures Thanks for pointing out such a critical bug.

RedDownloader 4.1.2 has been yanked from releases and replaced by RedDownloader 4.2.0 please kindly switch to the latest version to enojy everything RedDownloader has to offer

Once again Thank You
